name: test

on:
  pull_request:
  push:
    branches:
      - main

env:
  PYTHON_VERSION: "3.11.x"

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "${{ env.PYTHON_VERSION }}"
      - run: pip install pre-commit
      - uses: actions/cache@v3
        id: pre-commit-cache
        with:
          path: ~/.cache/pre-commit
          key: key-0
      - run: pip install printf-log-formatter black isort
      - run: pre-commit run --all-files

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.11.x" ]
        pydantic-version: [ "1.10.15", "2.7.1" ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python-version }}"
          pydantic-version: "${{ matrix.pydantic-version }}"
      - uses: actions/cache@v3
        id: poetry-cache
        with:
          path: ~/.local
          key: ${{ matrix.python-version }}{{ matrix.pydantic-version }}-0
      - uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false
          version: latest
      - uses: actions/cache@v3
        id: cache-venv
        with:
          path: .venv
          key: ${{ hashFiles('**/poetry.lock') }}-${{ matrix.python-version }}-0
      - run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -U pip
          poetry install --no-interaction --no-root --with=development
        if: steps.cache-venv.outputs.cache-hit != 'true'
      - run: |
          source .venv/bin/activate
          pip install pydantic=={{ pydantic-version }}

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: redis-tools
          version: 0

      - name: Run tests
        run: |
          docker compose up -d
          chmod +x ./setup-cluster.sh
          ./setup-cluster.sh
          source .venv/bin/activate
          coverage run -m pytest tests
          coverage xml
          coverage report
